### ISSUE TITLE
Problema con conexión a CSReporter WS

### ISSUE THREAD

**Issue by LARGH** [ConroeSoluciones/CSReporter-API-Java#1]
Uno de los problemas que tengo es para realizar la descarga de facturas usando CSReporter API.

Ejemplo de código:

1. Credenciales csCredenciales = new Credenciales("XXXXXXXXXXXX", "XXXXXXXX"); // Clave CIEF
2. CSReporter csReporter = new CSReporterImpl(csCredenciales, 100);
3. try {
4.      Consulta consulta = csReporter.consultar(csCredenciales,
5.			        new ParametrosBuilder()
6.			        .tipo(Parametros.Tipo.EMITIDAS)
7.			        .status(Parametros.Status.TODOS)
8.			        .fechaInicio(new DateTime()
9.			                .withDate(2014, 1, 1)
10.			                .withTimeAtStartOfDay()
11.			                .toDate())
12.			        .fechaFin(new DateTime()
13.			                .withDate(2015, 12, 31)
14.			                .withTime(23, 59, 59, 0)
15.			                .toDate())
16.			        .build(),
17.			        new ProgresoConsultaListener() {
18.					public void onStatusChanged(Status status, Consulta consulta) {
19.			            if (consulta.isTerminada()) {
20.			                for (int i = 1; i <= consulta.getPaginas(); i++) {
21.			                    List<CFDIMeta> cfdis = consulta.getResultados(i);
22.			                    if (cfdis.size() > 0) {
23.			                    	System.out.println("Mayor a cero...");
24.			                    } else {
25.			                    	System.out.println("Igual a cero...");
26.			                    }
28.			                }
29.			            }
30.					}
31.			        });
32.		} catch (ConsultaInvalidaException e) {
33.			e.printStackTrace();
34.		}

StackTrace:
Response: 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /webservices/csdescargasat/webservices/csdescargasat was not found on this server.</p>
<hr>
<address>Apache/2.2.15 (CentOS) Server at www.csfacturacion.com Port 443</address>
</body></html> 

Exception in thread "main" com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
	at com.google.gson.JsonParser.parse(JsonParser.java:65)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at com.csfacturacion.csreporter.impl.http.Response.getAsJson(Response.java:35)
	at com.csfacturacion.csreporter.impl.CSReporterImpl.consultar(CSReporterImpl.java:145)
	at api.tester.ws.test_ws_api.App.globalSetUp(App.java:65)
	at api.tester.ws.test_ws_api.App.main(App.java:104)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1566)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1416)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:546)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:429)
	at com.google.gson.JsonParser.parse(JsonParser.java:60)
	... 5 more

Lo que quiero ver es si el problema es si desde la API la URL se está construyendo mal.

**Comment by emerinohdz** [comment]
Hola @LARGH, para utiilizar este servicio es necesario que tengas contratado el servicio CSReporter con CSFacturación. 

Por favor ponte en contacto con ellos si estás interesado, esta API sólo funciona con un contrato de CSReporter.


Saludos.

**Comment by LARGH** [comment]
hola que tal @emerinohdz , resulta ser que tengo un usuario y contraseña de pruebas que me brindaron el personal de CSFacturación, y también probé la dicho usuario y contraseña pero tampoco.

**Comment by emerinohdz** [comment]
Ponte en contacto por favor con personal de CSFacturación, para que puedan brindarte el apoyo necesario.

Saludos.

**Comment by emerinohdz** [comment]
Por favor, consulta este archivo donde se puede apreciar el correcto uso de la API (en caso que tu problema sea efectivamente que no se está usando correctamente).

https://github.com/ConroeSoluciones/CSReporter-API-Java/blob/master/src/test/java/com/csfacturacion/csreporter/impl/CSReporterIT.java

Si los problemas persisten, por favor comunícate con personal de CSFacturación para que ellos te puedan brindar el soporte que necesitas.

Saludos.

**Comment by emerinohdz** [comment]
Hola @LARGH, había un error introducido en el último commit realizado, se corrigió y la versión que está en la rama "master" debe funcionar sin problemas.

Se está publicando la versión arreglada (1.1.1) a Maven Central y estará disponible en algunos minutos más.

Gracias por el reporte.
